# Read the documentation: https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
# See the official DoctrineExtensions documentation for more details: https://github.com/Atlantic18/DoctrineExtensions/tree/master/doc/
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            loggable: true
            sluggable: true

            # dont use it, it is incompatible with ODM which would prevent us
            # from switching to MongoDB, also the query filter seems not to work
            # every time -> handle manually
            softdeleteable: false

            sortable: true
            timestampable: true