vich_uploader:
    db_driver: orm
    mappings:
        public_file:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'type', transliterate: true}
        private_file:
            upload_destination: '%kernel.project_dir%/var/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'type', transliterate: true}
