version: '2'
services:
  mysql:
    image: mariadb:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fcp_test
      MYSQL_USER: fcp_test
      MYSQL_PASSWORD: fcp_test
  php:
    build: php
    container_name: php
    links:
      - mysql
    volumes:
      - ../:/var/www/html
    environment:
      APP_ENV: test
      XDEBUG_CONFIG: remote_host=host.docker.internal